
# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- qa
- uat
stages:
- stage: Deploy
  jobs:
  - job: Deploy_QA
    condition: eq(variables['Build.SourceBranchName'], 'qa')
    container: pricefx/pfxpackage:latest
    steps:
    - script: pfxpackage -import -timeout 120 -url ${URL} -user ${PFX_USER} -password $(PFX_PASS) -partition ${PARTITION} -from . ${OPTIONS}
      displayName: 'Deploy QA'
      env:
        PARTITION: partition-qa
        URL: https://qa.pricefx.eu
  - job: Deploy_PROD
    condition: eq(variables['Build.SourceBranchName'], 'master')
    container: pricefx/pfxpackage:latest
    steps:
      - script: pfxpackage -import -timeout 120 -url ${URL} -user ${PFX_USER} -password $(PFX_PASS) -partition ${PARTITION} -from . ${OPTIONS}
        displayName: 'Deploy PROD'
        env:
          PARTITION: partition-uat
          URL: https://www.pricefx.eu